### ISSUE TITLE
The individual grade feature is broken

### ISSUE THREAD

**Issue by phunlh2001** [Kunniii/edn_auto_ext#3]
Specifically, I'm not able to grade myself in EduNext but your extension automatically graded me, falsifying the score when announcing the final results. 

This would be harmful if there was censorship from the school.

**Comment by Kunniii** [comment]
# 😉

Isn't it a feature? Since the purpose of Edunext's Backend is just to read and save data to the Database with no sanitize, no validate, no nothing with the given data. The Frontend provided is just a way to truncate some of the user's abilities which is provided BY the API.

Let's just enjoy the unlocked power that this Extension gave you.

Plus, this extension DOES NOT STEAL your information, bare that in mind, because some does.

**Comment by Kunniii** [comment]
Just kidding! I will work on the issue this weekend! 

### Feel free to contribute your solution and make a pull request, I will review allllll of them!!

**Comment by phunlh2001** [comment]
the eduNext's dev resolved :)))
